name: CI

on: [push]

jobs:
  build:
    runs-on: rhel-8
    env:
      #NEXUS_USER: ${{ secrets.NEXUS_USER }}
      #NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      PATH: /home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
    steps:
    - uses: actions/checkout@v2
    - name: Python3.10
      run: |
        BUILD=${GITHUB_SHA:0:7}
        docker build -f Dockerfile-3.10-alpine --build-arg BUILD=$BUILD . \
                     -t oitacr.azurecr.io/pmartin47/salt:3.10-$BUILD-alpine \
                     -t oitacr.azurecr.io/pmartin47/salt:$BUILD-alpine \
                     -t oitacr.azurecr.io/pmartin47/salt:3.10-$BUILD \
                     -t oitacr.azurecr.io/pmartin47/salt:$BUILD
    - name: Python3.9
      run: |
        BUILD=${GITHUB_SHA:0:7}
        docker build -f Dockerfile-3.9-alpine --build-arg BUILD=$BUILD . \
                     -t oitacr.azurecr.io/pmartin47/salt:3.9-$BUILD-alpine \
                     -t oitacr.azurecr.io/pmartin47/salt:$BUILD-alpine \
                     -t oitacr.azurecr.io/pmartin47/salt:3.9-$BUILD \
                     -t oitacr.azurecr.io/pmartin47/salt:$BUILD
