name: Latest Release
run-name: "Latest Release (branch: ${{ github.ref_name }})"

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+-[0-9]+'

jobs:

  build-python3-12-3007:
    runs-on: ubuntu-22.04
    env:
      DOCKER_USERNAME: pcm0
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ACR_URL: ${{ secrets.ACR_URL }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Get Build Version
      run: |
        echo "BUILD=${GITHUB_REF:10}" | tee -a $GITHUB_ENV
        echo "SHORT_SHA=${GITHUB_SHA:0:7}" | tee -a $GITHUB_ENV
    - name: Python 3.12
      continue-on-error: true
      run: |
        podman pull python:3.12-alpine
        podman build -f Python-3.12-alpine.dockerfile --build-arg FLAGS='--no-deps' --build-arg REQUIREMENTS=requirements-3007.txt . \
                     -t docker.io/pcm0/salt:3.12-latest-alpine \
                     -t docker.io/pcm0/salt:3.12-${{ env.BUILD }}-alpine \
                     -t docker.io/pcm0/salt:3.12-latest \
                     -t docker.io/pcm0/salt:3.12-${{ env.BUILD }} \
                     -t docker.io/pcm0/salt:3.12-${{ env.SHORT_SHA }}-alpine \
                     -t $ACR_URL/pmartin47/salt:3.12-latest-alpine \
                     -t $ACR_URL/pmartin47/salt:3.12-${{ env.BUILD }}-alpine \
                     -t $ACR_URL/pmartin47/salt:3.12-latest \
                     -t $ACR_URL/pmartin47/salt:3.12-${{ env.BUILD }} \
                     -t $ACR_URL/pmartin47/salt:3.12-${{ env.SHORT_SHA }}-alpine
    - name: Push to Docker Hub
      run: |
        podman login docker.io --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        podman images | awk "/docker.io\/pcm0\/salt/&&/${{ env.BUILD }}/ { print \$1\":\"\$2 }" | xargs -I {} podman push {}
        podman logout
        podman login $ACR_URL --username $ACR_USERNAME --password $ACR_PASSWORD
        podman images | awk "/$ACR_URL\/pmartin47\/salt/&&/${{ env.BUILD }}/ { print \$1\":\"\$2 }" | xargs -I {} podman push {}

    - name: Docker System Prune
      run: |
        podman system prune --force --all
  build-python3-12-3007-isalt:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: pcm0
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ACR_URL: ${{ secrets.ACR_URL }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Get Build Version
      run: |
        echo "BUILD=${GITHUB_REF:10}" | tee -a $GITHUB_ENV
        echo "SHORT_SHA=${GITHUB_SHA:0:7}" | tee -a $GITHUB_ENV
    - name: Python 3.12
      continue-on-error: true
      run: |
        podman pull python:3.12-alpine
        podman build -f Python-3.12-alpine.dockerfile --build-arg FLAGS='--no-deps' --build-arg REQUIREMENTS=requirements-3007-isalt.txt . \
                     -t docker.io/pcm0/salt:3.12-latest-isalt-alpine \
                     -t docker.io/pcm0/salt:3.12-${{ env.BUILD }}-isalt-alpine \
                     -t docker.io/pcm0/salt:3.12-latest-isalt \
                     -t docker.io/pcm0/salt:3.12-${{ env.BUILD }}-isalt \
                     -t docker.io/pcm0/salt:3.12-${{ env.SHORT_SHA }}-isalt-alpine \
                     -t $ACR_URL/pmartin47/salt:3.12-latest-isalt-alpine \
                     -t $ACR_URL/pmartin47/salt:3.12-${{ env.BUILD }}-isalt-alpine \
                     -t $ACR_URL/pmartin47/salt:3.12-latest-isalt \
                     -t $ACR_URL/pmartin47/salt:3.12-${{ env.BUILD }}-isalt \
                     -t $ACR_URL/pmartin47/salt:3.12-${{ env.SHORT_SHA }}-isalt-alpine
    - name: Push to Docker Hub
      run: |
        podman login docker.io --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        podman images | awk "/docker.io\/pcm0\/salt/&&/${{ env.BUILD }}/ { print \$1\":\"\$2 }" | xargs -I {} podman push {}
        podman logout
        podman login $ACR_URL --username $ACR_USERNAME --password $ACR_PASSWORD
        podman images | awk "/$ACR_URL\/pmartin47\/salt/&&/${{ env.SHORT_BUILDSHA }}/ { print \$1\":\"\$2 }" | xargs -I {} podman push {}
  build-python3-11-3007:
    runs-on: ubuntu-22.04
    env:
      DOCKER_USERNAME: pcm0
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ACR_URL: ${{ secrets.ACR_URL }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Get Build Version
      run: |
        echo "BUILD=${GITHUB_REF:10}" | tee -a $GITHUB_ENV
        echo "SHORT_SHA=${GITHUB_SHA:0:7}" | tee -a $GITHUB_ENV
    - name: Python 3.11
      continue-on-error: true
      run: |
        podman pull python:3.11-alpine
        podman build -f Python-3.11-alpine.dockerfile --build-arg FLAGS='--no-deps' --build-arg REQUIREMENTS=requirements-3007.txt . \
                     -t docker.io/pcm0/salt:3.11-latest-alpine \
                     -t docker.io/pcm0/salt:3.11-${{ env.BUILD }}-alpine \
                     -t docker.io/pcm0/salt:3.11-latest \
                     -t docker.io/pcm0/salt:latest \
                     -t docker.io/pcm0/salt:3.11-${{ env.BUILD }} \
                     -t docker.io/pcm0/salt:3.11-${{ env.SHORT_SHA }}-alpine \
                     -t $ACR_URL/pmartin47/salt:3.11-latest-alpine \
                     -t $ACR_URL/pmartin47/salt:3.11-${{ env.BUILD }}-alpine \
                     -t $ACR_URL/pmartin47/salt:3.11-latest \
                     -t $ACR_URL/pmartin47/salt:latest \
                     -t $ACR_URL/pmartin47/salt:3.11-${{ env.BUILD }} \
                     -t $ACR_URL/pmartin47/salt:3.11-${{ env.SHORT_SHA }}-alpine
    - name: Push to Docker Hub
      run: |
        podman login docker.io --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        podman images | awk "/docker.io\/pcm0\/salt/&&/${{ env.BUILD }}/ { print \$1\":\"\$2 }" | xargs -I {} podman push {}
        podman logout
        podman login $ACR_URL --username $ACR_USERNAME --password $ACR_PASSWORD
        podman images | awk "/$ACR_URL\/pmartin47\/salt/&&/${{ env.BUILD }}/ { print \$1\":\"\$2 }" | xargs -I {} podman push {}

    - name: Docker System Prune
      run: |
        podman system prune --force --all
  build-python3-11-3007-isalt:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: pcm0
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ACR_URL: ${{ secrets.ACR_URL }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Get Build Version
      run: |
        echo "BUILD=${GITHUB_REF:10}" | tee -a $GITHUB_ENV
        echo "SHORT_SHA=${GITHUB_SHA:0:7}" | tee -a $GITHUB_ENV
    - name: Python 3.11
      continue-on-error: true
      run: |
        podman pull python:3.11-alpine
        podman build -f Python-3.11-alpine.dockerfile --build-arg FLAGS='--no-deps' --build-arg REQUIREMENTS=requirements-3007-isalt.txt . \
                     -t docker.io/pcm0/salt:3.11-latest-isalt-alpine \
                     -t docker.io/pcm0/salt:3.11-${{ env.BUILD }}-isalt-alpine \
                     -t docker.io/pcm0/salt:3.11-latest-isalt \
                     -t docker.io/pcm0/salt:latest-isalt \
                     -t docker.io/pcm0/salt:3.11-${{ env.BUILD }}-isalt \
                     -t docker.io/pcm0/salt:3.11-${{ env.SHORT_SHA }}-isalt-alpine \
                     -t $ACR_URL/pmartin47/salt:3.11-latest-isalt-alpine \
                     -t $ACR_URL/pmartin47/salt:3.11-${{ env.BUILD }}-isalt-alpine \
                     -t $ACR_URL/pmartin47/salt:3.11-latest-isalt \
                     -t $ACR_URL/pmartin47/salt:latest-isalt \
                     -t $ACR_URL/pmartin47/salt:3.11-${{ env.BUILD }}-isalt \
                     -t $ACR_URL/pmartin47/salt:3.11-${{ env.SHORT_SHA }}-isalt-alpine
    - name: Push to Docker Hub
      run: |
        podman login docker.io --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        podman images | awk "/docker.io\/pcm0\/salt/&&/${{ env.BUILD }}/ { print \$1\":\"\$2 }" | xargs -I {} podman push {}
        podman logout
        podman login $ACR_URL --username $ACR_USERNAME --password $ACR_PASSWORD
        podman images | awk "/$ACR_URL\/pmartin47\/salt/&&/${{ env.SHORT_BUILDSHA }}/ { print \$1\":\"\$2 }" | xargs -I {} podman push {}
    - name: Create a Release
      uses: ncipollo/release-action@v1
      with:
        #artifacts: "release.tar.gz,foo/*.txt"
        #bodyFile: "body.md"
        token: ${{ secrets.RELEASE_TOKEN }}
        name:  ${{ github.ref_name }}
        body: |+
          CHANGELOG:
          ${{ github.event.head_commit.message }}

          To download this release:
          podman pull docker.io/pcm0/salt

          Or to specify a build:
          podman pull docker.io/pcm0/salt:3.11-${{ env.BUILD }}-alpine
    - name: Docker System Prune
      run: |
        podman system prune --force --all

  build-python3-11-3006:
    runs-on: ubuntu-22.04
    env:
      DOCKER_USERNAME: pcm0
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ACR_URL: ${{ secrets.ACR_URL }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Get Build Version
      run: |
        echo "BUILD=${GITHUB_REF:10}" | tee -a $GITHUB_ENV
        echo "SHORT_SHA=${GITHUB_SHA:0:7}" | tee -a $GITHUB_ENV
    - name: Python 3.11
      continue-on-error: true
      run: |
        podman pull python:3.11-alpine
        podman build -f Python-3.11-alpine.dockerfile --build-arg FLAGS='--no-deps' --build-arg REQUIREMENTS=requirements-3006.txt . \
                     -t docker.io/pcm0/salt:3.11-3006.7-alpine \
                     -t docker.io/pcm0/salt:3.11-3006-alpine \
                     -t docker.io/pcm0/salt:3.11-3006.7 \
                     -t docker.io/pcm0/salt:3.11-3006 \
                     -t docker.io/pcm0/salt:3006 \
                     -t docker.io/pcm0/salt:3.11-3006.7-${{ env.SHORT_SHA }} \
                     -t docker.io/pcm0/salt:3.11-3006.7-${{ env.SHORT_SHA }}-alpine \
                     -t docker.io/pcm0/salt:3.11-3006-${{ env.SHORT_SHA }}-alpine \
                     -t docker.io/pcm0/salt:3.11-3006-${{ env.SHORT_SHA }} \
                     -t $ACR_URL/pmartin47/salt:3.11-3006.7-alpine \
                     -t $ACR_URL/pmartin47/salt:3.11-3006-alpine \
                     -t $ACR_URL/pmartin47/salt:3.11-3006.7 \
                     -t $ACR_URL/pmartin47/salt:3.11-3006 \
                     -t $ACR_URL/pmartin47/salt:3.3006 \
                     -t $ACR_URL/pmartin47/salt:3.11-3006.7-${{ env.SHORT_SHA }}-alpine \
                     -t $ACR_URL/pmartin47/salt:3.11-3006-${{ env.SHORT_SHA }}-alpine \
                     -t $ACR_URL/pmartin47/salt:3.11-3006.7-${{ env.SHORT_SHA }} \
                     -t $ACR_URL/pmartin47/salt:3.11-3006-${{ env.SHORT_SHA }}
    - name: Push to Docker Hub
      run: |
        podman login docker.io --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        podman images | awk "/docker.io\/pcm0\/salt/&&/${{ env.BUILD }}/ { print \$1\":\"\$2 }" | xargs -I {} podman push {}
        podman logout
        podman login $ACR_URL --username $ACR_USERNAME --password $ACR_PASSWORD
        podman images | awk "/$ACR_URL\/pmartin47\/salt/&&/${{ env.BUILD }}/ { print \$1\":\"\$2 }" | xargs -I {} podman push {}

    - name: Docker System Prune
      run: |
        podman system prune --force --all

  build-python3-11-3006-isalt:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: pcm0
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ACR_URL: ${{ secrets.ACR_URL }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Get Build Version
      run: |
        echo "BUILD=${GITHUB_REF:10}" | tee -a $GITHUB_ENV
        echo "SHORT_SHA=${GITHUB_SHA:0:7}" | tee -a $GITHUB_ENV
    - name: Python 3.11
      continue-on-error: true
      run: |
        podman pull python:3.11-alpine
        podman build -f Python-3.11-alpine.dockerfile --build-arg FLAGS='--no-deps' --build-arg REQUIREMENTS=requirements-3006-isalt.txt . \
                     -t docker.io/pcm0/salt:3.11-3006.7-isalt-alpine \
                     -t docker.io/pcm0/salt:3.11-3006-isalt-alpine \
                     -t docker.io/pcm0/salt:3.11-3006.7-isalt \
                     -t docker.io/pcm0/salt:3.11-3006-isalt \
                     -t docker.io/pcm0/salt:3006-isalt \
                     -t docker.io/pcm0/salt:3.11-3006.7-${{ env.SHORT_SHA }}-isalt-alpine \
                     -t docker.io/pcm0/salt:3.11-3006.7-${{ env.SHORT_SHA }}-isalt \
                     -t docker.io/pcm0/salt:3.11-3006-${{ env.SHORT_SHA }}-isalt-alpine \
                     -t docker.io/pcm0/salt:3.11-3006-${{ env.SHORT_SHA }}-isalt \
                     -t $ACR_URL/pmartin47/salt:3.11-3006.7-isalt-alpine \
                     -t $ACR_URL/pmartin47/salt:3.11-3006-isalt-alpine \
                     -t $ACR_URL/pmartin47/salt:3.11-3006.7-isalt \
                     -t $ACR_URL/pmartin47/salt:3.11-3006-isalt \
                     -t $ACR_URL/pmartin47/salt:3006-isalt \
                     -t $ACR_URL/pmartin47/salt:3.11-3006.7-${{ env.SHORT_SHA }}-isalt-alpine \
                     -t $ACR_URL/pmartin47/salt:3.11-3006.7-${{ env.SHORT_SHA }}-isalt \
                     -t $ACR_URL/pmartin47/salt:3.11-3006-${{ env.SHORT_SHA }}-isalt-alpine \
                     -t $ACR_URL/pmartin47/salt:3.11-3006-${{ env.SHORT_SHA }}-isalt
    - name: Push to Docker Hub
      run: |
        podman login docker.io --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        podman images | awk "/docker.io\/pcm0\/salt/&&/${{ env.BUILD }}/ { print \$1\":\"\$2 }" | xargs -I {} podman push {}
        podman logout
        podman login $ACR_URL --username $ACR_USERNAME --password $ACR_PASSWORD
        podman images | awk "/$ACR_URL\/pmartin47\/salt/&&/${{ env.SHORT_BUILDSHA }}/ { print \$1\":\"\$2 }" | xargs -I {} podman push {}
