name: Latest Python 3.12 Debian Release
run-name: "Latest Python 3.12 Debian Release (branch: ${{ github.ref_name }})"
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+-[0-9]+'
jobs: {}
