name: Unstable Release

on:
  push:
    # Pattern matched against refs/tags
    branches:
      - master
    tags:
      - '![0-9]+.[0-9]+-[0-9]+a[0-9]+'
      - '![0-9]+.[0-9]+-[0-9]+b[0-9]+'
      - '![0-9]+.[0-9]+-[0-9]+'

jobs:
  build:
    runs-on: rhel-8
    env:
      OITACR_USERNAME: ${{ secrets.OITACR_USERNAME }}
      OITACR_PASSWORD: ${{ secrets.OITACR_PASSWORD }}
      PATH: /home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
    steps:
    - uses: actions/checkout@v2
    - name: Get Build Version
      run: |
        echo "SHORT_SHA=${GITHUB_SHA:0:7}" | tee -a $GITHUB_ENV
    - name: Python 3.11
      continue-on-error: true
      run: |
        docker pull python:3.11-rc-alpine
        docker build -f Dockerfile-3.11-alpine --build-arg BUILD=${{ env.SHORT_SHA }} . \
                     -t oitacr.azurecr.io/pmartin47/salt:3.11-${{ env.SHORT_SHA }}-alpine
    - name: Python 3.10
      run: |
        docker pull python:3.10-alpine
        docker build -f Dockerfile-3.10-alpine --build-arg BUILD=${{ env.SHORT_SHA }} . \
                     -t oitacr.azurecr.io/pmartin47/salt:3.10-${{ env.SHORT_SHA }}-alpine
    - name: Python 3.9
      run: |
        docker pull python:3.9-alpine
        docker build -f Dockerfile-3.9-alpine --build-arg BUILD=${{ env.SHORT_SHA }} . \
                     -t oitacr.azurecr.io/pmartin47/salt:3.9-${{ env.SHORT_SHA }}-alpine
    - name: Push to OIT Azure Container Registry (oitacr)
      run: |
        docker login oitacr.azurecr.io --username $OITACR_USERNAME --password $OITACR_PASSWORD
        docker images | awk "/oitacr.azurecr.io\/pmartin47\/salt/&&/${{ env.SHORT_SHA }}/ { print \$1\":\"\$2 }" | xargs -I {} docker push {}
    - name: Docker System Prune
      run: |
        docker system prune --force --all
