name: Unstable Release

on:
  push:
    # Pattern matched against refs/tags
    branches:
      - master
    tags:
      - '![0-9]+.[0-9]+-[0-9]+a[0-9]+'
      - '![0-9]+.[0-9]+-[0-9]+b[0-9]+'
      - '![0-9]+.[0-9]+-[0-9]+'

jobs:

  build-python3-11:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: pcm0
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ACR_URL: ${{ secrets.ACR_URL }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Get Build Version
      run: |
        echo "SHORT_SHA=${GITHUB_SHA:0:7}" | tee -a $GITHUB_ENV
    - name: Python 3.11
      continue-on-error: true
      run: |
        docker pull python:3.11-alpine
        docker build -f Dockerfile-3.11-alpine --build-arg BUILD=${{ env.SHORT_SHA }} . \
                     -t pcm0/salt:3.11-${{ env.SHORT_SHA }}-alpine \
                     -t $ACR_URL/pmartin47/salt:3.11-${{ env.SHORT_SHA }}-alpine
    - name: Push to Docker Hub
      run: |
        docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        docker images | awk "/pcm0\/salt/&&/${{ env.SHORT_SHA }}/ { print \$1\":\"\$2 }" | xargs -I {} docker push {}
        docker logout
        docker login $ACR_URL --username $ACR_USERNAME --password $ACR_PASSWORD
        docker images | awk "/$ACR_URL\/pmartin47\/salt/&&/${{ env.SHORT_SHA }}/ { print \$1\":\"\$2 }" | xargs -I {} docker push {}
    - name: Docker System Prune
      run: |
        docker system prune --force --all

  build-python3-11-isalt:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: pcm0
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ACR_URL: ${{ secrets.ACR_URL }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Get Build Version
      run: |
        echo "SHORT_SHA=${GITHUB_SHA:0:7}" | tee -a $GITHUB_ENV
        echo "ipython" | tee -a requirements-3.11.txt
        echo "isalt" | tee -a requirements-3.11.txt
        echo "asttokens==2.0.8" | tee -a requirements-3.11.txt
        echo "backcall==0.2.0" | tee -a requirements-3.11.txt
        echo "decorator==5.1.1" | tee -a requirements-3.11.txt
        echo "executing==1.1.1" | tee -a requirements-3.11.txt
        echo "jedi==0.18.1" | tee -a requirements-3.11.txt
        echo "matplotlib-inline==0.1.6" | tee -a requirements-3.11.txt
        echo "parso==0.8.3" | tee -a requirements-3.11.txt
        echo "pexpect==4.8.0" | tee -a requirements-3.11.txt
        echo "pickleshare==0.7.5" | tee -a requirements-3.11.txt
        echo "prompt-toolkit==3.0.31" | tee -a requirements-3.11.txt
        echo "ptyprocess==0.7.0" | tee -a requirements-3.11.txt
        echo "pure-eval==0.2.2" | tee -a requirements-3.11.txt
        echo "pygments==2.13.0" | tee -a requirements-3.11.txt
        echo "six==1.16.0" | tee -a requirements-3.11.txt
        echo "stack-data==0.5.1" | tee -a requirements-3.11.txt
        echo "traitlets==5.5.0" | tee -a requirements-3.11.txt
        echo "wcwidth==0.2.5" | tee -a requirements-3.11.txt
    - name: Python 3.11
      continue-on-error: true
      run: |
        docker pull python:3.11-alpine
        docker build -f Dockerfile-3.11-alpine --build-arg BUILD=${{ env.SHORT_SHA }} . \
                     -t pcm0/salt:3.11-isalt-${{ env.SHORT_SHA }}-alpine \
                     -t $ACR_URL/pmartin47/salt:3.11-isalt-${{ env.SHORT_SHA }}-alpine
    - name: Push to Docker Hub
      run: |
        docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        docker images | awk "/pcm0\/salt/&&/${{ env.SHORT_SHA }}/ { print \$1\":\"\$2 }" | xargs -I {} docker push {}
        docker logout
        docker login $ACR_URL --username $ACR_USERNAME --password $ACR_PASSWORD
        docker images | awk "/$ACR_URL\/pmartin47\/salt/&&/${{ env.SHORT_SHA }}/ { print \$1\":\"\$2 }" | xargs -I {} docker push {}
    - name: Docker System Prune
      run: |
        docker system prune --force --all

  build-python3-10:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: pcm0
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ACR_URL: ${{ secrets.ACR_URL }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Get Build Version
      run: |
        echo "SHORT_SHA=${GITHUB_SHA:0:7}" | tee -a $GITHUB_ENV
        echo "ipython" | tee -a requirements.txt
        echo "isalt" | tee -a requirements.txt
    - name: Python 3.10
      run: |
        docker pull python:3.10-alpine
        docker build -f Dockerfile-3.10-alpine --build-arg BUILD=${{ env.SHORT_SHA }} . \
                     -t pcm0/salt:3.10-${{ env.SHORT_SHA }}-alpine \
                     -t $ACR_URL/pmartin47/salt:3.10-${{ env.SHORT_SHA }}-alpine
    - name: Push to Docker Hub
      run: |
        docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        docker images | awk "/pcm0\/salt/&&/${{ env.SHORT_SHA }}/ { print \$1\":\"\$2 }" | xargs -I {} docker push {}
        docker logout
        docker login $ACR_URL --username $ACR_USERNAME --password $ACR_PASSWORD
        docker images | awk "/$ACR_URL\/pmartin47\/salt/&&/${{ env.SHORT_SHA }}/ { print \$1\":\"\$2 }" | xargs -I {} docker push {}
    - name: Docker System Prune
      run: |
        docker system prune --force --all

  build-python3-10-isalt:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: pcm0
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ACR_URL: ${{ secrets.ACR_URL }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Get Build Version
      run: |
        echo "SHORT_SHA=${GITHUB_SHA:0:7}" | tee -a $GITHUB_ENV
    - name: Python 3.10
      run: |
        docker pull python:3.10-alpine
        docker build -f Dockerfile-3.10-alpine --build-arg BUILD=${{ env.SHORT_SHA }} . \
                     -t pcm0/salt:3.10-isalt-${{ env.SHORT_SHA }}-alpine \
                     -t $ACR_URL/pmartin47/salt:3.10-isalt-${{ env.SHORT_SHA }}-alpine
    - name: Push to Docker Hub
      run: |
        docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        docker images | awk "/pcm0\/salt/&&/${{ env.SHORT_SHA }}/ { print \$1\":\"\$2 }" | xargs -I {} docker push {}
        docker logout
        docker login $ACR_URL --username $ACR_USERNAME --password $ACR_PASSWORD
        docker images | awk "/$ACR_URL\/pmartin47\/salt/&&/${{ env.SHORT_SHA }}/ { print \$1\":\"\$2 }" | xargs -I {} docker push {}
    - name: Docker System Prune
      run: |
        docker system prune --force --all
      
